// --- Studio Assistant Note ---
// This file is considered LOCKED and should not be modified.
// The user has requested to keep the current header design permanent.
// Do not edit this file without explicit user confirmation.
// --- End Studio Assistant Note ---

"use client";

import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

const HEADER_SETTINGS_KEY = 'aparra-header-settings';

interface HeaderSettings {
  logoWidth: number; // e.g., 8 (maps to h-8, w-8)
  hideOnScroll: boolean;
}

const defaultSettings: HeaderSettings = {
  logoWidth: 8,
  hideOnScroll: true,
};

interface HeaderSettingsContextType {
  settings: HeaderSettings;
  setSetting: <K extends keyof HeaderSettings>(key: K, value: HeaderSettings[K]) => void;
  isMounted: boolean;
}

const HeaderSettingsContext = createContext<HeaderSettingsContextType | undefined>(undefined);

export const HeaderSettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [settings, setSettings] = useState<HeaderSettings>(defaultSettings);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    try {
      const storedSettings = localStorage.getItem(HEADER_SETTINGS_KEY);
      if (storedSettings) {
        setSettings({ ...defaultSettings, ...JSON.parse(storedSettings) });
      }
    } catch (error) {
      console.error("Failed to read header settings from localStorage", error);
    }
  }, []);

  useEffect(() => {
    if (isMounted) {
      try {
        localStorage.setItem(HEADER_SETTINGS_KEY, JSON.stringify(settings));
        window.dispatchEvent(new StorageEvent('storage', {
            key: HEADER_SETTINGS_KEY,
            newValue: JSON.stringify(settings),
        }));
      } catch (error) {
        console.error("Failed to write header settings to localStorage", error);
      }
    }
  }, [settings, isMounted]);

  const setSetting = useCallback(<K extends keyof HeaderSettings>(key: K, value: HeaderSettings[K]) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  }, []);

  useEffect(() => {
    if (!isMounted) return;

    const handleStorageChange = (event: StorageEvent) => {
      if (event.key === HEADER_SETTINGS_KEY && event.newValue) {
        setSettings({ ...defaultSettings, ...JSON.parse(event.newValue) });
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => {
      window.removeEventListener('storage', handleStorageChange);
    };
  }, [isMounted]);

  const value = useMemo(() => ({
    settings,
    setSetting,
    isMounted,
  }), [settings, setSetting, isMounted]);

  return (
    <HeaderSettingsContext.Provider value={value}>
      {children}
    </HeaderSettingsContext.Provider>
  );
};

export const useHeaderSettings = () => {
  const context = useContext(HeaderSettingsContext);
  if (context === undefined) {
    throw new Error('useHeaderSettings must be used within a HeaderSettingsProvider');
  }
  return context;
};
