
// --- Studio Assistant Note ---
// This file is considered LOCKED and should not be modified.
// The user has requested to keep the current header design permanent.
// Do not edit this file without explicit user confirmation.
// --- End Studio Assistant Note ---

"use client";

import Link from "next/link";
import Image from "next/image";
import { ShoppingBag, Heart, MapPin } from "lucide-react";
import React, { useState, useEffect } from "react";

import { useCart } from "@/hooks/use-cart.tsx";
import { useWishlist } from "@/hooks/use-wishlist.tsx";
import { useSiteLogo } from "@/hooks/use-site-logo.tsx";
import { useHeaderSettings } from "@/hooks/use-header-settings.tsx";
import { Icons } from "@/components/icons";
import { Button } from "@/components/ui/button";
import type { Menu, Category, MenuItem } from "@/lib/types";
import { useMenu } from "@/hooks/use-menu.tsx";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import { cn } from "@/lib/utils";
import * as LucideIcons from "lucide-react";
import { Image as ImageIcon } from "lucide-react";
import { UserMenu } from "@/auth/components/user-menu";
import { ProductSearchBar } from "../products/product-search-bar";

type IconName = keyof typeof LucideIcons;

const Icon = ({ name, className }: { name: string | null; className: string }) => {
  if (!name || typeof name !== 'string') {
    return null;
  }
  const LucideIcon = LucideIcons[name as IconName];
  if (!LucideIcon) {
    return <ImageIcon className={className} />;
  }
  return <LucideIcon className={className} />;
};

const ListItem = React.forwardRef<
  HTMLAnchorElement,
  {
    title: string;
    href: string;
    icon?: string | null;
  }
>(({ title, href, icon }, ref) => {
  return (
    <Link
      ref={ref}
      href={href}
      className="group flex items-center gap-4 text-foreground hover:text-primary transition-all"
    >
      <div className="flex items-center justify-center p-2.5 rounded-md bg-accent text-accent-foreground group-hover:bg-secondary">
        <Icon name={icon} className="h-5 w-5" />
      </div>
      <span className="text-[15px] font-medium tracking-wide group-hover:font-semibold">
        {title}
      </span>
    </Link>
  );
});
ListItem.displayName = "ListItem";


function PromoCard({
  title,
  subtitle,
  image,
  href,
}: {
  title?: string | null;
  subtitle?: string | null;
  image?: string | null;
  href?: string | null;
}) {
  if (!href || !image) return null;

  return (
    <Link href={href} className="group block">
      <div className="overflow-hidden rounded-xl">
        <Image
          src={image}
          alt={title || ''}
          width={400}
          height={500}
          className="h-[260px] w-full object-cover transition-transform duration-700 group-hover:scale-105"
        />
      </div>

      <div className="mt-4 text-center">
        {title && <h4 className="text-[16px] font-semibold tracking-wide">
          {title}
        </h4>}
        {subtitle && (
          <p className="mt-1 text-sm text-muted-foreground">
            {subtitle}
          </p>
        )}
      </div>
    </Link>
  );
}

const MainNav = ({ menu, categories }: { menu: Menu | null, categories: Category[] }) => {
    if (!menu) {
        return <nav className="flex items-center gap-6 text-sm"></nav>
    }

    const topLevelItems = menu.items.filter(item => !item.parent_id).sort((a,b) => a.sort_order - b.sort_order);
    const getChildren = (parentId: string) => menu.items.filter(item => item.parent_id === parentId).sort((a,b) => a.sort_order - b.sort_order);

    return (
        <NavigationMenu>
            <NavigationMenuList className="justify-between w-full">
                {topLevelItems.map(item => {
                    const children = getChildren(item.id);
                    if (children.length > 0) {
                        const hasPromo = item.promoImageUrl || item.promo2ImageUrl;
                        return (
                             <NavigationMenuItem key={item.id} value={item.id}>
                                <NavigationMenuTrigger>{item.label}</NavigationMenuTrigger>
                                <NavigationMenuContent>
                                    <div className="mx-auto max-w-7xl px-10 py-12">
                                        <div className="mb-10 h-px w-full bg-border" />
                                        {hasPromo ? (
                                            <div className="grid grid-cols-12 gap-x-14 gap-y-10">
                                                {/* LEFT — SUB CATEGORIES */}
                                                <div className="col-span-12 lg:col-span-7 grid grid-cols-3 gap-y-8 gap-x-12">
                                                    {children.map((child) => (
                                                        <ListItem
                                                            key={child.id}
                                                            title={child.label}
                                                            href={child.link}
                                                            icon={child.icon}
                                                        />
                                                    ))}
                                                </div>

                                                {/* RIGHT — PROMOTIONAL CARDS */}
                                                <div className="col-span-12 lg:col-span-5 grid grid-cols-2 gap-8">
                                                    <PromoCard
                                                        title={item.promoTitle}
                                                        subtitle={item.promoDescription}
                                                        image={item.promoImageUrl}
                                                        href={item.promoLink}
                                                    />
                                                    <PromoCard
                                                        title={item.promo2Title}
                                                        subtitle={item.promo2Description}
                                                        image={item.promo2ImageUrl}
                                                        href={item.promo2Link}
                                                    />
                                                </div>
                                            </div>
                                        ) : (
                                            <div className="grid grid-cols-4 gap-x-12 gap-y-8">
                                                 {children.map((child) => (
                                                    <ListItem
                                                        key={child.id}
                                                        title={child.label}
                                                        href={child.link}
                                                        icon={child.icon}
                                                    />
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </NavigationMenuContent>
                            </NavigationMenuItem>
                        )
                    }
                    return (
                        <NavigationMenuItem key={item.id}>
                            <Link href={item.link} legacyBehavior passHref>
                            <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                                {item.label}
                            </NavigationMenuLink>
                            </Link>
                        </NavigationMenuItem>
                    )
                })}
            </NavigationMenuList>
        </NavigationMenu>
    )
}


export function Header() {
  const { cartCount, isCartReady } = useCart();
  const { wishlistCount, isWishlistReady } = useWishlist();
  const { siteLogoUrl } = useSiteLogo();
  const { settings, isMounted } = useHeaderSettings();
  const { menu, categories, isLoading: isLoadingMenu } = useMenu();
  const [scrolled, setScrolled] = useState(false);
  const [visible, setVisible] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  const handleScroll = () => {
    const isScrolled = window.scrollY > 20;
    setScrolled(isScrolled);

    if (settings.hideOnScroll) {
        const currentScrollY = window.scrollY;
        if (currentScrollY > lastScrollY && currentScrollY > 150) {
            setVisible(false);
        } else {
            setVisible(true);
        }
        setLastScrollY(currentScrollY);
    } else {
        setVisible(true);
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [lastScrollY, settings.hideOnScroll]);

  if (!isMounted || isLoadingMenu) {
      return (
        <header className="fixed top-0 z-50 w-full h-28 bg-background">
            <div className="container mx-auto h-full flex items-center justify-between">
                <div className="h-10 w-32 bg-muted rounded-md animate-pulse" />
                <div className="flex items-center gap-8">
                     <div className="h-8 w-48 bg-muted rounded-md animate-pulse" />
                     <div className="h-8 w-48 bg-muted rounded-md animate-pulse" />
                     <div className="h-8 w-48 bg-muted rounded-md animate-pulse" />
                </div>
                 <div className="h-10 w-32 bg-muted rounded-md animate-pulse" />
            </div>
        </header>
      )
  }

  return (
    <header className={cn(
        "fixed top-0 z-50 w-full transition-all duration-300",
        visible ? "translate-y-0" : "-translate-y-full"
    )}>
       <div className={cn(
           "bg-secondary text-secondary-foreground text-xs transition-all duration-300",
           scrolled && settings.hideOnScroll ? 'h-0 py-0 opacity-0 overflow-hidden' : 'h-8'
        )}>
           <div className="container mx-auto flex h-full items-center justify-between px-6">
                <div className="flex items-center gap-6">
                    <Link href="/track-order" className="flex items-center gap-1.5 hover:text-primary transition-colors">
                        <span>Track Order</span>
                    </Link>
                    <Link href="/find-a-store" className="flex items-center gap-1.5 hover:text-primary transition-colors">
                        <MapPin className="h-3 w-3" />
                        <span>Find a Store</span>
                    </Link>
                </div>
                 <div className="flex items-center gap-6">
                    {/* Search Bar - Small, left of User Menu */}
                    <div className="w-48">
                        <ProductSearchBar />
                    </div>
                    <UserMenu />
                </div>
           </div>
       </div>

       <div className={cn(
           "w-full border-b transition-all duration-300", 
           scrolled ? "bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 shadow-md" : "bg-transparent border-transparent"
        )}>
            <div className="container mx-auto flex flex-col">
                <div className="flex h-20 items-center justify-between">
                    {/* Left Section */}
                    <div className="flex flex-1 items-center justify-start">
                    <Link href="/" className="flex items-center space-x-2">
                        {siteLogoUrl ? (
                        <Image
                            src={siteLogoUrl}
                            alt="Aparra"
                            width={settings.logoWidth * 4}
                            height={settings.logoWidth * 4}
                            className="object-contain w-auto"
                            style={{height: `${settings.logoWidth * 4}px`}}
                        />
                        ) : (
                        <Icons.logo className="text-primary w-auto" style={{height: `${settings.logoWidth * 4}px`}} />
                        )}
                    </Link>
                    </div>
                    
                    {/* Center Section */}
                    <div className="hidden md:flex flex-1 items-center justify-center">
                        <MainNav menu={menu} categories={categories} />
                    </div>

                    {/* Right Section */}
                    <div className="flex flex-1 items-center justify-end space-x-1">
                        <Button variant="ghost" size="icon" asChild>
                            <Link href="/wishlist">
                                <div className="relative">
                                    <Heart className="h-5 w-5" />
                                    {isWishlistReady && wishlistCount > 0 && (
                                        <span className="absolute -top-2 -right-2 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                                            {wishlistCount}
                                        </span>
                                    )}
                                </div>
                                <span className="sr-only">Wishlist</span>
                            </Link>
                        </Button>
                        <Button variant="ghost" size="icon" asChild>
                        <Link href="/cart">
                            <div className="relative">
                            <ShoppingBag className="h-5 w-5" />
                            {isCartReady && cartCount > 0 && (
                                <span className="absolute -top-2 -right-2 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                                {cartCount}
                                </span>
                            )}
                            </div>
                            <span className="sr-only">Shopping Cart</span>
                        </Link>
                        </Button>
                    </div>
                </div>
            </div>
       </div>
    </header>
  );
}
