
// --- Studio Assistant Note ---
// This file is considered LOCKED and should not be modified.
// The user has requested to keep the current header design permanent.
// Do not edit this file without explicit user confirmation.
// --- End Studio Assistant Note ---

"use client";

import Link from "next/link";
import Image from "next/image";
import { ShoppingBag, Search, Menu as MenuIcon, X, Heart } from "lucide-react";
import React, { useState, useEffect } from "react";

import { useCart } from "@/hooks/use-cart.tsx";
import { useWishlist } from "@/hooks/use-wishlist.tsx";
import { useSiteLogo } from "@/hooks/use-site-logo.tsx";
import { useHeaderSettings } from "@/hooks/use-header-settings.tsx";
import { Icons } from "@/components/icons";
import { Button } from "@/components/ui/button";
import { useMenu } from "@/hooks/use-menu.tsx";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTrigger,
} from "@/components/ui/sheet";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { cn } from "@/lib/utils";
import { UserMenu } from "@/auth/components/user-menu";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ProductSearchBar } from "../products/product-search-bar";

const MobileNav = () => {
    const { menu, isLoading } = useMenu();

    if (isLoading || !menu) {
        return (
            <div className="space-y-4">
                <div className="h-8 w-3/4 bg-muted rounded-md animate-pulse" />
                <div className="h-8 w-1/2 bg-muted rounded-md animate-pulse" />
                <div className="h-8 w-2/3 bg-muted rounded-md animate-pulse" />
            </div>
        )
    }
    
    const topLevelItems = menu.items.filter(item => !item.parent_id).sort((a,b) => a.sort_order - b.sort_order);
    const getChildren = (parentId: string) => menu.items.filter(item => item.parent_id === parentId).sort((a,b) => a.sort_order - b.sort_order);

    return (
        <Accordion type="multiple" className="w-full">
            {topLevelItems.map(item => {
                const children = getChildren(item.id);
                if (children.length > 0) {
                    return (
                        <AccordionItem value={item.id} key={item.id}>
                            <AccordionTrigger className="text-lg font-semibold">
                                {item.label}
                            </AccordionTrigger>
                            <AccordionContent>
                                <div className="flex flex-col space-y-1 pl-4">
                                     <Link href={item.link} className="py-2 text-muted-foreground hover:text-foreground">
                                        All {item.label}
                                    </Link>
                                    {children.map(child => (
                                        <Link key={child.id} href={child.link} className="py-2 text-muted-foreground hover:text-foreground flex items-center gap-3">
                                            {child.imageUrl && <Image src={child.imageUrl} alt={child.label} width={24} height={24} className="rounded-sm" />}
                                            <span>{child.label}</span>
                                        </Link>
                                    ))}
                                </div>
                            </AccordionContent>
                        </AccordionItem>
                    )
                }
                return (
                    <Link key={item.id} href={item.link} className="block border-b py-4 text-lg font-semibold">
                        {item.label}
                    </Link>
                )
            })}
        </Accordion>
    )
}


export function MobileHeader() {
  const { cartCount, isCartReady } = useCart();
  const { wishlistCount, isWishlistReady } = useWishlist();
  const { siteLogoUrl } = useSiteLogo();
  const { settings } = useHeaderSettings();
  const [open, setOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);

  const logoHeight = settings.logoWidth * 4; 

  return (
    <header className="fixed top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container mx-auto flex h-16 items-center justify-between px-4 gap-2">
        
        {isSearchOpen ? (
            <div className="flex-1">
                <ProductSearchBar />
            </div>
        ) : (
            <>
                <Sheet open={open} onOpenChange={setOpen}>
                    <SheetTrigger asChild>
                        <Button variant="ghost" size="icon" className="-ml-2">
                        <MenuIcon className="h-6 w-6" />
                        <span className="sr-only">Open Menu</span>
                        </Button>
                    </SheetTrigger>
                    <SheetContent side="left" className="w-full max-w-sm flex flex-col p-0">
                        <SheetHeader className="p-6 pb-4 border-b">
                            <Link href="/" className="mb-4" onClick={() => setOpen(false)}>
                                {siteLogoUrl ? (
                                <Image 
                                    src={siteLogoUrl} 
                                    alt="Aparra" 
                                    width={logoHeight * 2} 
                                    height={logoHeight} 
                                    className={cn("object-contain w-auto")} 
                                    style={{height: `${logoHeight}px`}}
                                />
                                ) : (
                                <Icons.logo className="w-auto text-primary" style={{height: `${logoHeight}px`}} />
                                )}
                            </Link>
                        </SheetHeader>
                        <ScrollArea className="flex-1">
                            <div className="p-6">
                                <MobileNav />
                            </div>
                        </ScrollArea>
                    </SheetContent>
                </Sheet>
                
                <div className={cn("flex items-center justify-center flex-1")}>
                    <Link href="/">
                        {siteLogoUrl ? (
                            <Image 
                            src={siteLogoUrl} 
                            alt="Aparra" 
                            width={logoHeight * 2.5} 
                            height={logoHeight} 
                            className={cn("object-contain w-auto")} 
                            style={{height: `${logoHeight}px`}}
                            />
                        ) : (
                            <Icons.logo className="w-auto text-primary" style={{height: `${logoHeight}px`}} />
                        )}
                    </Link>
                </div>
            </>
        )}
        
        <div className="flex items-center space-x-0">
            <Button variant="ghost" size="icon" onClick={() => setIsSearchOpen(prev => !prev)}>
                {isSearchOpen ? <X className="h-5 w-5" /> : <Search className="h-5 w-5" />}
                <span className="sr-only">{isSearchOpen ? "Close search" : "Open search"}</span>
            </Button>
             <Button variant="ghost" size="icon" asChild>
                <Link href="/wishlist">
                    <div className="relative">
                        <Heart className="h-5 w-5" />
                        {isWishlistReady && wishlistCount > 0 && (
                            <span className="absolute -top-1 -right-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                                {wishlistCount}
                            </span>
                        )}
                    </div>
                    <span className="sr-only">Wishlist</span>
                </Link>
            </Button>
            <Button variant="ghost" size="icon" asChild>
                <Link href="/cart">
                <div className="relative">
                    <ShoppingBag className="h-5 w-5" />
                    {isCartReady && cartCount > 0 && (
                    <span className="absolute -top-1 -right-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                        {cartCount}
                    </span>
                    )}
                </div>
                <span className="sr-only">Shopping Cart</span>
                </Link>
            </Button>
            <UserMenu />
        </div>
      </div>
    </header>
  );
}
