// --- Studio Assistant Note ---
// This file is considered LOCKED and should not be modified.
// The user has requested to keep the current header design permanent.
// Do not edit this file without explicit user confirmation.
// --- End Studio Assistant Note ---

"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { useHeaderSettings } from "@/hooks/use-header-settings.tsx";

export function MobileHeaderSettingsForm() {
    const { settings, setSetting } = useHeaderSettings();

    return (
        <div className="space-y-6">
            <Card>
                <CardHeader>
                    <CardTitle>Mobile Logo Settings</CardTitle>
                    <CardDescription>Adjust the size of your logo on mobile devices.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="space-y-2">
                        <Label>Logo Size</Label>
                        <div className="flex items-center gap-4">
                            <Slider
                                value={[settings.logoWidth]}
                                onValueChange={([value]) => setSetting('logoWidth', value)}
                                min={4}
                                max={12}
                                step={1}
                            />
                            <span className="text-sm text-muted-foreground w-12 text-right">{settings.logoWidth * 4}px</span>
                        </div>
                         <p className="text-xs text-muted-foreground">Controls the height of the logo on mobile.</p>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
